### ISSUE TITLE
Can keywords be lowercase?

### ISSUE THREAD

**Issue by shelverizr** [isoos/query#12]
In my use case, the query string that needs to be parsed comes from user input. It would be great if keywords can be lowercase, which can reduce the time and effort spent by users on input.

Finally, please allow me to offer you my most sincere respect. Thank you for all your contributions!

**Comment by isoos** [comment]
To clarify, we are talking about the `AND`, `OR` and `NOT` expressions, am I correct? I think it is possible to do that, but it may be a breaking case for some users, so it should be a configuration option. Is that something you are looking for?

**Comment by shelverizr** [comment]
Sorry for only getting back to you now. My answer is: Yes, but I found that I can just use `-` `|` instead of `NOT` and `OR`, and spaces instead of `AND`. There is no need to think about case anymore.
