### ISSUE TITLE
Query doesn't handle nested boolean queries

### ISSUE THREAD

**Issue by edyu** [isoos/query#2]
For example: (A OR NOT ( B AND C ) ) are not handled properly. ( are not handled as priority grouping. They are parsed as TextQuery.

**Comment by edyu** [comment]
I might just rewrite it and if so I'll send a pull request if my changes are not too massive. Thanks for the work.

**Comment by isoos** [comment]
@edyu PRs are welcome, please also add a few tests to it, to make sure it won't break later on.

**Comment by edyu** [comment]
@isoos #3 submitted. I didn't update the test file except to make it passing with the extra parenthesis. (I think it would make sense to not use parentheses for printing AND or OR to differentiate against grouping but I didn't want to make the change because it would break almost all your current tests. I did a lot of testing on my own but didn't use your test file. I'll see if I get around to add some tests to the query test file.

**Comment by edyu** [comment]
release 1.3.0 fixed this so I'm closing it.
